version: "{build}"
branches:
  only:
  - master
  - /v\d+\..+/
  - /release.*/
  - appveyor
  - hunter
clone_depth: 100
os: "Visual Studio 2015"
environment:
  matrix:
  - CUDA_VER: "9.0"
  - CUDA_VER: "10.0"
  HUNTER_CACHE_TOKEN:
    secure: VnpF1MH5MEFvUI5MiMMMFlmbDdst+bfom5ZFVgalYPp/SYDhbejjXJm9Dla/IgpC

# Download CUDA Windows installer (local) and extract /compiler/* to /CUDA/vX.0/ zip archive.
install: |
  git submodule update --init --recursive
  set CUDA_ARCHIVE=CUDA-v%CUDA_VER%-WindowsServer2012.7z
  appveyor DownloadFile https://github.com/ethereum-mining/ethminer/releases/download/build-deps/%CUDA_ARCHIVE%
  7z x %CUDA_ARCHIVE% -oC:\
  set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%;C:\CUDA\v%CUDA_VER%\bin
  pip install requests gitpython
  nvcc -V
build_script:
- cmake --build build --config Release --target package
- ps: |
    . build/ethminer/buildinfo.ps1
    mv build/ethminer.zip build/$env:project_name-$env:project_version-cuda$env:CUDA_VER-$env:system_name-$env:system_processor.zip
artifacts:
- path: build/ethminer-*.zip
  name: ethminer

deploy:
  # Create GitHub release, also set the release name and description.
  provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: "$(project_name) $(project_version)"
  description: ""
  force_update: true  # Force update in case Travis CI created the release before.
  prerelease: $(project_version_is_prerelease)
  draft: false
  artifact: ethminer
  auth_token:
    secure: uDRcvbW+9GIyKlZ9guJfWOQ6jg0An6eULg6mEkYgdKn/GVNpYSKvO5oHxP0U8a+e
  on:
    appveyor_repo_tag: true